### ISSUE TITLE
The marathon mode's loading speed is too slow

### ISSUE THREAD

**Issue by Oibeck** [bunyodrafikov/autotest-android#37]

**Comment by bunyodrafikov** [comment]
Maybe too low?

**Comment by Oibeck** [comment]
For Samsung S10, it's about 18 seconds
For Samsung S22, it's 4-5 seconds

**Comment by Oibeck** [comment]
Should be added at least a loading screen that will indicate loading progress in percentage

**Comment by bunyodrafikov** [comment]
- [ ] Create an AnsweredQuestion Entity with properties: 
- > Quiz Id
- > Question id 
- > Answer position 
- > Is answer Correct

- [ ] Create List of AnsweredQuestions in adapter and bind the result if it is exsisting

- [ ] Everytime when ViewPager’s page opened, check is there any answered question with the same id in the list within adapter

- [ ] After quiz has finished, send list of answered questions to one database

- [ ] When quiz opened, in QuizViewmodel get the list of answered questions by quiz id. If it is NOT emty or null show dialog do you want to continue or re-try if see results, then bind the results
