### ISSUE TITLE
Upscale the quality of the media for additional 300 questions

### ISSUE THREAD

**Issue by Oibeck** [bunyodrafikov/autotest-android#38]

**Comment by Oibeck** [comment]
The media of the 300 questions has poor quality, and also watermarks in some cases. They should be upscaled, and the watermarks should be removed

**Comment by bunyodrafikov** [comment]
@Oibeck We can do it simply with the help of AI 😃

**Comment by Oibeck** [comment]
I've already upscaled them, but I'm not sure whether they can remove watermarks or not🥲(I tried with online services and also with pdf editor but nothing had worked). Probably I'll do it manually using Pixelmator Pro
